export const MAX_STICKER_PACK_NAME_LENGTH = 20

export const MIN_STICKER_PACK_USERNAME_LENGTH = 3
export const MAX_STICKER_PACK_USERNAME_LENGTH = 32
export const STICKER_PACK_USERNAME_PATTERN = /^[a-zA-Z0-9_]+$/

export const MAX_STICKERS_PER_PACK = 120
