export enum UploadCategory {
	IMAGE = 'IMAGE',
	VIDEO = 'VIDEO',
	VOICE = 'VOICE',
	FILE = 'FILE',
	STICKER = 'STICKER',
	EMOJI = 'EMOJI',
	AVATAR = 'AVATAR',
	VIDEO_STICKER = 'VIDEO_STICKER',
	VIDEO_EMOJI = 'VIDEO_EMOJI',
	VIDEO_AVATAR = 'VIDEO_AVATAR'
}
